# Generated by Django 5.1.4 on 2024-12-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Completed', 'Completed')], default='pending', max_length=80),
        ),
    ]
